# Generated by Django 5.1.2 on 2024-10-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_streaks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificacion",
            old_name="ususario",
            new_name="usuario",
        ),
        migrations.RenameField(
            model_name="preferenciasnotificacion",
            old_name="recibir_promociones",
            new_name="recibir_notificaciones",
        ),
    ]
