# Generated by Django 5.1.2 on 2024-10-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_streaks", "0002_rename_ususario_notificacion_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.CharField(
                choices=[
                    ("salud", "Salud"),
                    ("deporte", "Deporte"),
                    ("trabajo", "Trabajo"),
                    ("personal", "Personal"),
                ],
                default="uncategorized",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Diario"),
                    ("weekly", "Semanal"),
                    ("monthly", "Mensual"),
                ],
                max_length=50,
            ),
        ),
    ]
