# Generated by Django 5.1.2 on 2024-10-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_streaks", "0003_alter_habit_category_alter_habit_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="original_goal",
            field=models.IntegerField(default=1),
        ),
    ]
