# Generated by Django 5.1.2 on 2024-10-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_streaks", "0004_habit_original_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="creation_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
